# Generated by Django 3.0.3 on 2020-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_salary', models.PositiveIntegerField(default=0)),
                ('employee_age', models.PositiveIntegerField(default=0)),
                ('profile_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
