# Generated by Django 3.0.3 on 2020-03-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='profile_img',
            new_name='profile_image',
        ),
    ]
